import Head from "next/head";


function Header() {
    return (
        <Head>
            <title>Dora The Explorer</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}


export default Header;